name: Appium Mobile Automation Tests

on:
  push:
    branches: [ "main", "havva/qa" ]
  pull_request:
    branches: [ "main" ]

jobs:
  android-tests:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Appium Server & Drivers
        run: |
          npm install -g appium@latest
          appium driver install uiautomator2

      - name: Run Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          script: |
            appium &
            sleep 5
            mvn test