name: Appium Mobile Automation Tests

on:
  push:
    branches: [ "main", "havva/qa" ]
  pull_request:
    branches: [ "main" ]

jobs:
  android-tests:
    # 1. Burayı tekrar macos yapıyoruz (Emülatörün sorunsuz açılması için)
    runs-on: macos-13

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install Node.js & Appium
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 2. Burayı appium@latest olarak güncelliyoruz (Sürüm hatasını çözmek için)
      - name: Install Appium Server & Drivers
        run: |
          npm install -g appium@latest
          appium driver install uiautomator2

      - name: Run Appium Tests on Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          script: mvn test